---
- name: Remove timesyncd configuration based on files
  become: true
  ansible.builtin.file:
    path: "{{ timesyncd_file_path }}/{{ item | basename }}"
    state: absent
  with_fileglob:
    - "{{ timesyncd_local_path }}/*.conf"
  notify: restart systemd-timesyncd

- name: Remove timesyncd configuration based on templates
  become: true
  ansible.builtin.file:
    path: "{{ timesyncd_file_path }}/{{ item | basename | splitext | first }}"
    state: absent
  with_fileglob:
    - "{{ timesyncd_local_path }}/*.conf.j2"
  notify: restart systemd-timesyncd

- name: Ensure timezone is set to default
  become: true
  community.general.timezone:
    name: "{{ timesyncd_default_timezone }}"
  notify: restart systemd-timesyncd
