---
- name: Change ntp in timesyncd configuration
  when: timesyncd_ntp | length > 0
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: "^#?NTP="
    line: "NTP={{ timesyncd_ntp }}"
  notify: restart systemd-timesyncd

- name: Restore ntp in timesyncd configuration
  when: timesyncd_ntp | length == 0
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: "^#?NTP="
    line: "#NTP="
  notify: restart systemd-timesyncd

- name: Change fallback_ntp in timesyncd configuration
  when: timesyncd_fallback_ntp | length > 0
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: "^#?FallbackNTP="
    line: "FallbackNTP={{ timesyncd_fallback_ntp }}"
  notify: restart systemd-timesyncd

- name: Restore fallback_ntp in timesyncd configuration
  when: timesyncd_fallback_ntp | length == 0
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: "^#?FallbackNTP="
    line: "#FallbackNTP=ntp.ubuntu.com"
  notify: restart systemd-timesyncd

- name: Change root_distance_max_sec in timesyncd configuration
  when: timesyncd_root_distance_max_sec | length > 0
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: "^#?RootDistanceMaxSec="
    line: "RootDistanceMaxSec={{ timesyncd_root_distance_max_sec }}"
  notify: restart systemd-timesyncd

- name: Restore root_distance_max_sec in timesyncd configuration
  when: timesyncd_root_distance_max_sec | length == 0
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: "^#?RootDistanceMaxSec="
    line: "#RootDistanceMaxSec=5"
  notify: restart systemd-timesyncd

- name: Change poll_interval_min_sec in timesyncd configuration
  when: timesyncd_poll_interval_min_sec | length > 0
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: "^#?PollIntervalMinSec="
    line: "PollIntervalMinSec={{ timesyncd_poll_interval_min_sec }}"
  notify: restart systemd-timesyncd

- name: Restore poll_interval_min_sec in timesyncd configuration
  when: timesyncd_poll_interval_min_sec | length == 0
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: "^#?PollIntervalMinSec="
    line: "#PollIntervalMinSec=32"
  notify: restart systemd-timesyncd

- name: Change poll_interval_max_sec in timesyncd configuration
  when: timesyncd_poll_interval_max_sec | length > 0
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: "^#?PollIntervalMaxSec="
    line: "PollIntervalMaxSec={{ timesyncd_poll_interval_max_sec }}"
  notify: restart systemd-timesyncd

- name: Restore poll_interval_max_sec in timesyncd configuration
  when: timesyncd_poll_interval_max_sec | length == 0
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: "^#?PollIntervalMaxSec="
    line: "#PollIntervalMaxSec=2048"
  notify: restart systemd-timesyncd

- name: Set timezone
  when: timesyncd_timezone | length > 0
  become: yes
  community.general.timezone:
    name: "{{ timesyncd_timezone }}"
  notify: restart systemd-timesyncd
