---
- name: Add timesynced configuration
  ansible.builtin.include_tasks: install.yml
  when: timesynced_uninstall == false

- name: Remove timesynced configuration
  ansible.builtin.include_tasks: uninstall.yml
  when: timesynced_uninstall == true
