---
- name: Add timesynced configuration
  when: timesyncd_uninstall == false
  block:
    - name: Setup
      ansible.builtin.include_tasks: setup.yml

- name: Remove timesynced configuration
  when: timesyncd_uninstall == true
  block:
    - name: Clean
      ansible.builtin.include_tasks: clean.yml
