---
- name: Remove timesyncd config files
  become: true
  ansible.builtin.file:
    path: "{{ timesyncd_drop-in_path }}/{{ item | basename }}"
    state: absent
  with_fileglob:
    - "{{ timesyncd_local_path }}/*.conf"
  notify: restart systemd-timesyncd

- name: Ensure timezone is set to default
  become: true
  community.general.timezone:
    name: "{{ timesyncd_default_timezone }}"
  notify: restart systemd-timesyncd
